### ISSUE TITLE
Need help dockerizing the Next.js app that connects to database on build time

### ISSUE THREAD

**Issue by 4Furki4** [leerob/next-self-host#10]
Greetings folks,

I'm trying to self host my [project](https://github.com/4Furki4/Turkish-Dictionary) based on the Leerob's guide. The problem is that Leerob hosts a simple next.js application that doesn't generate dynamic metadata that queries the database. My next app tries to connect to the db on the build stage however, the postgres image doesn't boot up before the web image builds. I tried healthcheck and condition however, it still boots the web first and the build ends up with a connection error:

![Image](https://github.com/user-attachments/assets/fccc6b93-466b-4f56-a8e2-1d194609365f)

Here's my Dockerfile

````Dockerfile
FROM oven/bun:alpine AS base

# Stage 1: Install dependencies
FROM base AS deps
WORKDIR /app
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

# Stage 2: Build the application
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN SKIP_ENV_VALIDATION=1 bun run build
````

Here's my docker-compose.yaml

````yaml
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
volumes:
  postgres_data:

networks:
  my_network:
    name: my_network
    driver: bridge
````

Can anyone help me? This might also help others who try to connect to the db on the build stage.
